CalEvent = new Mongo.Collection('calevent');
Meteor.methods({
  saveCalEvent:function(ce){

        CalEvent.insert(ce);
      },
      updateTitle:function(id,title){
        return CalEvent.update({_id:id},{$set:{title:title}});
      },
      moveEvent:function(reqEvent){
        return CalEvent.update({_id:reqEvent._id},{
          $set:{
            start:reqEvent.start,
            end:reqEvent.end
          }
        })
      },
  deleteAccount: function(userId) {
    if (this.userId === userId) {
      return Meteor.users.remove({
        _id: this.userId
      });
    }
  }
});

// ---
// generated by coffee-script 1.9.2
